import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsBoolean, IsObject } from 'class-validator';
import { ReviewStatus } from '@inqi/shared';
import type { QuestionnaireAnswersDto as IAnswers } from '@inqi/shared';

/** Body for submitting questionnaire answers (tokened, no login). */
export class QuestionnaireAnswersDto implements IAnswers {
  @ApiProperty({ example: true, description: 'Customer confirms the subject is correct (mandatory gate).' })
  @IsBoolean()
  confirmedSubject!: boolean;

  @ApiProperty({ type: 'object', additionalProperties: { type: 'string' }, description: 'question id → the chosen option text (multi-choice joins selections with ", ")', example: { budget: '500-800', where: 'Amsterdam, 25km', when: 'within a month' } })
  @IsObject()
  answers!: Record<string, string>;
}

/** One scope question as generated by the questionnaire agent. */
export class QuestionDto {
  @ApiProperty({ example: 'budget_band', description: 'Stable snake_case id — the key in `answers`' })
  id!: string;

  @ApiProperty({ example: 'What is your realistic total budget?' })
  prompt!: string;

  @ApiProperty({ type: [String], example: ['Under €500', '€500 – €1,000', 'Over €1,000', 'Decide for me'], description: '3-4 concrete options + the automatic "Decide for me" fallback' })
  options!: string[];

  @ApiProperty({ example: false, description: 'true = additive dimension (pick ANY); false = exclusive (pick ONE)' })
  multi!: boolean;
}

/** Questionnaire as shown to the customer via the tokened link. */
export class QuestionnaireDto {
  @ApiProperty({ example: 'clz3q0001' })
  id!: string;

  @ApiProperty({ example: 'clz1abcd0000xy' })
  reportId!: string;

  @ApiProperty({ example: 'a1b2c3…' })
  token!: string;

  @ApiProperty({ type: [QuestionDto], description: '7-10 research-grounded scope questions' })
  questions!: unknown;

  @ApiProperty({ enum: Object.values(ReviewStatus), example: ReviewStatus.Passed })
  reviewStatus!: ReviewStatus;

  @ApiProperty({ example: false })
  confirmed!: boolean;

  @ApiProperty({ example: '2026-07-01T12:00:00.000Z' })
  expiresAt!: Date;
}

/** Result of submitting questionnaire answers. */
export class SubmitResultDto {
  @ApiProperty({ example: true })
  ok!: boolean;
}
